import type { Metadata } from "next";
import { Montserrat, Exo_2 } from "next/font/google";

import "@/styles/index.scss";

const montserrat = Montserrat({ subsets: ["latin", "cyrillic"] });
const exo = Exo_2({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
